name: 'Auto Release Milestone' 
description: 'A GitHub release draft based on a newly closed milestone'  
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN'
    required: true
outputs:
  release-url:
    description: 'The URL of the GitHub release draft'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.repo-token}}
