name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  building:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: build file via local make file
      run: |
          cd src
          make testing
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: src/
        
  test:
    
    runs-on: ubuntu-latest
    needs: building
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/download-artifact@v3
      with:
        name: artifacts
        path: src
    - name: Display structure of downloaded files
      run: | 
          ls
      working-directory: src
      
    - name: runs program
      run: |
        cd src
        chmod +x ./main
        ./main
        python3 count.py

    - name: clean program
      run: |
        cd src
        make clean
      
   
