name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: build file via local make file
      run: make testing
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: workflows/
  test: 
      runs-on: ubuntu-latest
      needs: build
      steps: 
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@main
        with:
          name: download artifact
          path: workflows
      - name: run file
        run: ./main
      

    #- name: Install dependencies
      #run: make
      
    #- name: Run check
      #run: make check
      
    #- name: Run distcheck
      #run: make distcheck
