name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 13 * * 1"
jobs:
  building:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    
    - name: build file via local make file
      run: |
        cd src
        make testing
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: src/
        
  test:
    
    runs-on: ubuntu-latest
    needs: building
    steps:
    - uses: actions/checkout@v3
    
    - name: Locate path
      shell: bash
      run: |
        pwd
        ls
        cd src
        ls


    - uses: actions/download-artifact@v3
      with:
        name: artifacts
        path: src/build
    - name: Display structure of downloaded files
      run: | 
          ls
      working-directory: src
      
    - name: runs program
      run: |
        cd src
        chmod +x ./main
        ./main
        python3 count.py

    - name: clean program
      run: |
        cd src
        make clean
      
   
