name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: build file via local make file
      run: make testing
      
    #- name: Install dependencies
      #run: make
      
    #- name: Run check
      #run: make check
      
    #- name: Run distcheck
      #run: make distcheck
