# This is a basic workflow to help you get started with Actions

name: pull request of a branch

# Controls when the workflow will run
on: 
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  notifying:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    
      #sending message to discord server
      - name: send message to discord server
        uses: ./.github/actions/discord_message
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#1ABC9C"
          username: "GitHub Action"
          message: ${{github.ref_name}} has ${{ github.event_name }}ed onto the repository
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build and test the code
        uses: ./.github/actions/build-and-test
        with: 
          repo-token: ${{secrets.GITHUB_TOKEN}}

        
      

